# Generated by Django 4.2.7 on 2023-12-12 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="customer",
        ),
        migrations.AddField(
            model_name="ride",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ride",
            name="end_location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ride",
            name="start_location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("unavailable", "Unavailable"),
                ],
                default="requested",
                max_length=50,
            ),
        ),
    ]
