# Generated by Django 4.2.7 on 2023-12-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_ride_customer_ride_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="end_name_location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="start_name_location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
