# Generated by Django 4.2.7 on 2024-01-06 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_email"),
        ("core", "0003_ride_end_name_location_ride_start_name_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="is_driver_location",
        ),
        migrations.RemoveField(
            model_name="location",
            name="user",
        ),
        migrations.AddField(
            model_name="location",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="user_type",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverschedule",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.driver"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_rides",
                to="users.driver",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
    ]
