# Generated by Django 4.2.7 on 2024-02-05 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_remove_location_is_driver_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("arrived", "Arrived"),
                    ("waiting_for_passenger", "Waiting for Passenger"),
                    ("in_progress", "In Progress"),
                    ("travelling", "Travelling"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("unavailable", "Unavailable"),
                ],
                default="requested",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RideStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("arrived", "Arrived"),
                            ("waiting_for_passenger", "Waiting for Passenger"),
                            ("in_progress", "In Progress"),
                            ("travelling", "Travelling"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=21,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="core.ride",
                    ),
                ),
            ],
        ),
    ]
