# Generated by Django 4.2.7 on 2024-01-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_customuser",
            field=models.BooleanField(default=True),
        ),
    ]
