# Generated by Django 4.2.7 on 2024-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_is_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="current_location_lat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="current_location_long",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
